(function () {
  "use strict";
  var workflowKey = "sial-mobile-workflow", hu591Key = "sial-mobile-hu591", pageKey = "sial-mobile-hu344", syncQueueKey = "sial-mobile-sync-queue", capacity = 48;
  var operations = [
    { id: "XD-2026-0418", zone: "ZE Puerto Norte", destination: "Puerto Amberes", references: [{ code: "BAN-REF-001", name: "Premium 22XU" }, { code: "BAN-REF-004", name: "Cluster 208" }], pallets: [
      { sscc: "177012345678900019", farmCode: "0435", farmName: "Finca La Bacota", reference: "BAN-REF-001", referenceName: "Premium 22XU", boxes: 30, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900026", farmCode: "0527", farmName: "Finca Santa Isabel", reference: "BAN-REF-001", referenceName: "Premium 22XU", boxes: 18, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900033", farmCode: "0412", farmName: "Finca La Esperanza", reference: "BAN-REF-001", referenceName: "Premium 22XU", boxes: 22, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900071", farmCode: "0435", farmName: "Finca La Bacota", reference: "BAN-REF-004", referenceName: "Cluster 208", boxes: 24, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900088", farmCode: "0527", farmName: "Finca Santa Isabel", boxes: 48, palletType: "MIXED", composition: [{ reference: "BAN-REF-001", referenceName: "Premium 22XU", boxes: 24 }, { reference: "BAN-REF-004", referenceName: "Cluster 208", boxes: 24 }], status: "DISPONIBLE_EN_ZE" }
    ] },
    { id: "XD-2026-0520", zone: "ZE Terminal Sur", destination: "Puerto Róterdam", references: [{ code: "BAN-REF-018", name: "Baby Banana" }, { code: "BAN-REF-022", name: "Orgánico 18KG" }], pallets: [
      { sscc: "177012345678900042", farmCode: "0527", farmName: "Finca Santa Isabel", reference: "BAN-REF-018", referenceName: "Baby Banana", boxes: 28, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900059", farmCode: "0412", farmName: "Finca La Esperanza", reference: "BAN-REF-018", referenceName: "Baby Banana", boxes: 20, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900066", farmCode: "0435", farmName: "Finca La Bacota", reference: "BAN-REF-022", referenceName: "Orgánico 18KG", boxes: 24, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900073", farmCode: "0527", farmName: "Finca Santa Isabel", boxes: 24, palletType: "MIXED", composition: [{ reference: "BAN-REF-018", referenceName: "Baby Banana", boxes: 12 }, { reference: "BAN-REF-022", referenceName: "Orgánico 18KG", boxes: 12 }], status: "DISPONIBLE_EN_ZE" }
    ] }
  ];
  var selectedOperation = null, selectedPallets = [], results = [], resultSequence = 0;
  function $(selector, root) { return (root || document).querySelector(selector); }
  function $all(selector, root) { return Array.from((root || document).querySelectorAll(selector)); }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function escapeHtml(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (char) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]; }); }
  function readJson(key, fallback) { try { return JSON.parse(localStorage.getItem(key) || "") || fallback; } catch (_) { return fallback; } }
  function writeJson(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
  function normalizeSscc(value) { if (window.SialMobileUI && typeof window.SialMobileUI.normalizeSscc === "function") return window.SialMobileUI.normalizeSscc(value); var digits = String(value || "").replace(/\D/g, ""); return digits.length === 20 && digits.slice(0, 2) === "00" ? digits.slice(2) : digits; }
  function checkDigit(body) { var sum = 0; for (var i = body.length - 1, weight = 3; i >= 0; i -= 1, weight = weight === 3 ? 1 : 3) sum += Number(body.charAt(i)) * weight; return String((10 - (sum % 10)) % 10); }
  function setNote(selector, message, type) { var node = $(selector); if (!node) return; node.textContent = message; node.className = "sial-field-note" + (type ? " " + type : ""); }
  function clearError(field) { if (field) { field.removeAttribute("aria-invalid"); field.classList.remove("sial-error-target"); } var error = $("[data-flow-error]"); if (error && window.SialMobileUI && typeof window.SialMobileUI.clearInlineStatus === "function") window.SialMobileUI.clearInlineStatus(error); else if (error) error.hidden = true; }
  function showError(message, field) { var error = $("[data-flow-error]"); if (window.SialMobileUI && typeof window.SialMobileUI.setInlineStatus === "function") window.SialMobileUI.setInlineStatus(error, { type: "error", title: "Revisa la conciliación", message: message, form: error.closest("form"), field: field }); else { error.hidden = false; error.textContent = message; (field || error).scrollIntoView({ behavior: "smooth", block: "center" }); } }
  function markDirty() { if (window.SialMobileUI && typeof window.SialMobileUI.markUnsavedChanges === "function") window.SialMobileUI.markUnsavedChanges("hu344"); }
  function allPallets() { return operations.reduce(function (list, operation) { return list.concat(operation.pallets.map(function (item) { return Object.assign({ operationId: operation.id, zone: operation.zone }, item); })); }, []); }
  function findOperation(id) { return operations.find(function (item) { return item.id === id; }) || null; }
  function palletType(item) { return item.palletType === "MIXED" || (Array.isArray(item.composition) && item.composition.length > 1) ? "MIXED" : "INCOMPLETE"; }
  function palletState(item) { return palletType(item) === "MIXED" ? "Mixto" : "Incompleto"; }
  function itemComposition(item) { return Array.isArray(item.composition) && item.composition.length ? item.composition : [{ reference: item.reference, referenceName: item.referenceName || "", boxes: Number(item.boxes || 0) }]; }
  function totalOriginBoxes() { return selectedPallets.reduce(function (sum, item) { return sum + Number(item.boxes || 0); }, 0); }
  function totalResultBoxes() { return results.reduce(function (sum, item) { return sum + Number(item.boxes || 0); }, 0); }
  function uniqueReferences() { return Object.keys(referenceTotals()); }
  function uniqueFarms() { return Array.from(new Set(selectedPallets.map(function (item) { return item.farmCode; }))); }
  function uniqueOperationIds() { return Array.from(new Set(selectedPallets.map(function (item) { return item.operationId; }).filter(Boolean))); }
  function uniqueZones() { return Array.from(new Set(selectedPallets.map(function (item) { return item.zone; }).filter(Boolean))); }
  function referenceInfo(code) { for (var p = 0; p < selectedPallets.length; p += 1) { var component = itemComposition(selectedPallets[p]).find(function (item) { return item.reference === code; }); if (component) return { code: code, name: component.referenceName || "" }; } for (var i = 0; i < operations.length; i += 1) { var match = operations[i].references.find(function (item) { return item.code === code; }); if (match) return match; } return { code: code, name: "" }; }
  function referenceTotals() { return selectedPallets.reduce(function (totals, item) { itemComposition(item).forEach(function (component) { totals[component.reference] = Number(totals[component.reference] || 0) + Number(component.boxes || 0); }); return totals; }, {}); }
  function hydrateInventoryAdjustments() { var state = readJson(pageKey, {}), adjustments = Array.isArray(state.inventoryAdjustments) ? state.inventoryAdjustments : []; operations.forEach(function (operation) { operation.pallets.forEach(function (item) { var adjustment = adjustments.find(function (candidate) { return candidate.sscc === item.sscc; }); if (adjustment) { item.boxes = Number(adjustment.remainingBoxes || 0); item.status = item.boxes > 0 ? "DISPONIBLE_EN_ZE" : adjustment.status; } }); }); }
  function availablePallets() { return allPallets().filter(function (item) { return item.status === "DISPONIBLE_EN_ZE" && Number(item.boxes) > 0; }); }
  function distributeEvenly(total, count) { var safe = Math.max(1, count), base = Math.floor(total / safe), extra = total % safe; return Array.from({ length: safe }, function (_, index) { return base + (index < extra ? 1 : 0); }); }
  function resultCounts() { return results.reduce(function (counts, item) { counts[item.reference] = Number(counts[item.reference] || 0) + 1; return counts; }, {}); }
  function resetResults(counts, preserve) { var totals = referenceTotals(), previous = preserve === false ? [] : results.slice(); results = []; Object.keys(totals).forEach(function (reference) { var minimum = Math.max(1, Math.ceil(totals[reference] / capacity)), desired = Math.max(minimum, Number((counts || {})[reference] || minimum)), amounts = distributeEvenly(totals[reference], desired), old = previous.filter(function (item) { return item.reference === reference; }); amounts.forEach(function (boxes, index) { results.push({ id: old[index] ? old[index].id : "result-" + (++resultSequence), reference: reference, sscc: old[index] ? old[index].sscc : "", boxes: boxes, scanSource: old[index] ? old[index].scanSource : "TYPED" }); }); }); }
  function reconcileAfterSelection() { selectedOperation = selectedPallets.length ? findOperation(selectedPallets[0].operationId) : null; resetResults({}, false); clearError(); render(); markDirty(); }

  function openPalletPicker() {
    var draft = selectedPallets.map(function (item) { return item.sscc; }), query = "", filter = "ALL", content = document.createElement("div"); content.className = "hu344-picker-shell";
    content.innerHTML = '<div class="hu344-picker-tools"><label class="hu344-picker-search"><svg class="sial-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg><input type="search" inputmode="search" autocomplete="off" placeholder="Buscar SSCC, referencia o finca" aria-label="Buscar pallets" data-hu344-picker-search></label><button class="sial-btn sial-btn-primary hu344-picker-scan" type="button" data-hu344-picker-scan aria-label="Escanear SSCC de pallet"><svg class="sial-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4M7 12h10"></path></svg><span>Escanear</span></button></div><div class="hu344-picker-filters" role="group" aria-label="Filtrar pallets por tipo"><button class="is-selected" type="button" aria-pressed="true" data-hu344-picker-filter="ALL">Todos</button><button type="button" aria-pressed="false" data-hu344-picker-filter="INCOMPLETE">Incompletos</button><button type="button" aria-pressed="false" data-hu344-picker-filter="MIXED">Mixtos</button></div><p class="hu344-picker-status" role="status" aria-live="polite" data-hu344-picker-status></p><div class="hu344-base-picker" data-hu344-picker-list></div>';
    var search = $("[data-hu344-picker-search]", content), list = $("[data-hu344-picker-list]", content), status = $("[data-hu344-picker-status]", content);
    function searchableText(item) { return [item.sscc, item.farmCode, item.farmName, item.zone, palletState(item)].concat(itemComposition(item).map(function (component) { return component.reference + " " + component.referenceName; })).join(" ").toLocaleLowerCase("es"); }
    function referenceLabel(item) { var references = itemComposition(item).map(function (component) { return component.reference; }); return references.length === 1 ? references[0] : references.length + " referencias"; }
    function draw() {
      var term = query.trim().toLocaleLowerCase("es"), available = availablePallets(), filtered = available.filter(function (item) { return filter === "ALL" || palletType(item) === filter; }); if (term) filtered = filtered.filter(function (item) { return searchableText(item).indexOf(term) >= 0; });
      status.textContent = term ? filtered.length + " coincidencia" + (filtered.length === 1 ? "" : "s") + " · " + draft.length + " seleccionado" + (draft.length === 1 ? "" : "s") : filtered.length + " pallet" + (filtered.length === 1 ? "" : "s") + (filter === "INCOMPLETE" ? " incompletos" : filter === "MIXED" ? " mixtos" : " disponibles") + " · " + draft.length + " seleccionado" + (draft.length === 1 ? "" : "s");
      list.innerHTML = filtered.length ? filtered.map(function (item) { var selected = draft.indexOf(item.sscc) >= 0, state = palletState(item), stateClass = palletType(item) === "MIXED" ? " info" : " warning"; return '<button class="hu344-picker-pallet' + (selected ? ' is-selected' : '') + '" type="button" aria-pressed="' + selected + '" data-hu344-picker-option="' + escapeHtml(item.sscc) + '"><span class="hu344-picker-content"><span class="hu344-picker-heading"><strong>' + escapeHtml(item.sscc) + '</strong><i class="sial-pill' + stateClass + '">' + state + '</i></span><span class="hu344-picker-details"><b>' + escapeHtml(referenceLabel(item)) + '</b><small>' + Number(item.boxes) + ' cajas</small></span><small class="hu344-picker-farm">' + escapeHtml(item.farmCode + " · " + item.farmName) + '</small></span><i class="hu344-picker-check" aria-hidden="true">' + (selected ? '✓' : '') + '</i></button>'; }).join("") : '<div class="hu344-picker-empty"><strong>Sin coincidencias</strong><span>Prueba con otro tipo, SSCC, referencia o finca.</span></div>';
    }
    function scanBasePallet() {
      var available = availablePallets();
      window.SialMobileUI.openBarcodeScanner({ title: "Escanear pallet base", eyebrow: "HU344 · Selección de origen", normalize: normalizeSscc, validate: function (value) { var code = normalizeSscc(value), match = available.find(function (item) { return item.sscc === code; }); return match ? { ok: true, message: "Pallet disponible para seleccionar." } : { ok: false, message: "El SSCC no corresponde a un pallet disponible en ZE." }; }, onDetected: function (value) { var code = normalizeSscc(value), match = available.find(function (item) { return item.sscc === code; }); if (draft.indexOf(code) < 0) draft.push(code); query = ""; search.value = ""; filter = match ? palletType(match) : "ALL"; $all("[data-hu344-picker-filter]", content).forEach(function (button) { var selected = button.dataset.hu344PickerFilter === filter; button.classList.toggle("is-selected", selected); button.setAttribute("aria-pressed", String(selected)); }); draw(); status.textContent = "Pallet " + code + " seleccionado por escaneo."; } });
    }
    search.addEventListener("input", function () { query = search.value; draw(); });
    content.addEventListener("click", function (event) { var filterButton = event.target.closest("[data-hu344-picker-filter]"); if (filterButton) { filter = filterButton.dataset.hu344PickerFilter; $all("[data-hu344-picker-filter]", content).forEach(function (button) { var selected = button === filterButton; button.classList.toggle("is-selected", selected); button.setAttribute("aria-pressed", String(selected)); }); draw(); return; } var scan = event.target.closest("[data-hu344-picker-scan]"); if (scan) { scanBasePallet(); return; } var button = event.target.closest("[data-hu344-picker-option]"); if (!button) return; var sscc = button.dataset.hu344PickerOption, index = draft.indexOf(sscc); if (index >= 0) draft.splice(index, 1); else draft.push(sscc); draw(); }); draw();
    window.SialMobileUI.openDialog({ id: "hu344-pallet-picker", variant: "sheet", title: "Seleccionar pallets", message: "Elige uno o varios pallets base. Cada pallet conserva los datos de su operación.", content: content, returnFocus: $("[data-hu344-select-base]"), actions: [{ label: "Cancelar", variant: "secondary" }, { label: "Usar selección", onClick: function () { selectedPallets = draft.map(function (sscc) { return clone(allPallets().find(function (item) { return item.sscc === sscc; })); }).filter(Boolean); reconcileAfterSelection(); } }] });
  }
  function removePallet(sscc) { selectedPallets = selectedPallets.filter(function (item) { return item.sscc !== sscc; }); reconcileAfterSelection(); }
  function allocationPlan() {
    var pools = []; selectedPallets.forEach(function (item) { itemComposition(item).forEach(function (component) { pools.push({ sscc: item.sscc, operationId: item.operationId, zone: item.zone, farmCode: item.farmCode, farmName: item.farmName, reference: component.reference, remaining: Number(component.boxes) }); }); });
    return results.map(function (result) {
      var needed = Number(result.boxes || 0), allocations = [];
      function take(pool, amount) { var quantity = Math.min(pool.remaining, amount); if (quantity > 0) { allocations.push({ sourceSscc: pool.sscc, operationId: pool.operationId, zone: pool.zone, farmCode: pool.farmCode, farmName: pool.farmName, reference: pool.reference, boxes: quantity }); pool.remaining -= quantity; needed -= quantity; } }
      while (needed > 0) { var candidate = pools.filter(function (item) { return item.reference === result.reference && item.remaining > 0; }).sort(function (a, b) { return b.remaining - a.remaining; })[0]; if (!candidate) break; take(candidate, needed); }
      return Object.assign({}, result, { allocations: allocations });
    });
  }
  function resultReferences(result) { return Array.from(new Set((result.allocations || []).map(function (item) { return item.reference; }))); }
  function allUsedSscc() { var hu591 = readJson(hu591Key, {}), workflow = readJson(workflowKey, {}), hu344 = readJson(pageKey, {}), ready = [].concat(hu591.readyPallets || [], workflow.readyPallets || []); return new Set([].concat(allPallets().map(function (item) { return item.sscc; }), hu591.usedSscc || [], workflow.usedSscc || [], hu344.usedSscc || [], ready.map(function (item) { return item.sscc; })).filter(Boolean)); }
  function validateResultSscc(value, index) { var code = normalizeSscc(value); if (code.length !== 18) return { ok: false, message: "El SSCC debe contener 18 dígitos." }; if (checkDigit(code.slice(0, 17)) !== code.slice(17)) return { ok: false, message: "El dígito de control no es válido." }; if (allUsedSscc().has(code)) return { ok: false, message: "Este SSCC ya pertenece a otro pallet." }; if (results.some(function (item, itemIndex) { return itemIndex !== index && normalizeSscc(item.sscc) === code; })) return { ok: false, message: "Este SSCC está repetido en los resultados." }; return { ok: true, message: "SSCC válido y disponible." }; }
  function scanResult(index) { window.SialMobileUI.openBarcodeScanner({ title: "Escanear pallet resultado", eyebrow: "Resultado " + String(index + 1).padStart(2, "0"), normalize: normalizeSscc, validate: function (value) { return validateResultSscc(value, index); }, onDetected: function (value) { results[index].sscc = normalizeSscc(value); results[index].scanSource = "SCANNED"; render(); markDirty(); } }); }
  function addResultFor(reference) { var counts = resultCounts(), total = Number(referenceTotals()[reference] || 0); if (!total || Number(counts[reference] || 0) >= total) return; counts[reference] = Number(counts[reference] || 0) + 1; resetResults(counts); render(); markDirty(); }
  function addResult() { var references = uniqueReferences(); if (!selectedPallets.length || !references.length) return; if (references.length === 1) { addResultFor(references[0]); return; } var content = document.createElement("div"); content.className = "hu344-reference-picker"; content.innerHTML = references.map(function (reference) { var info = referenceInfo(reference), total = referenceTotals()[reference]; return '<button type="button" data-hu344-result-reference="' + escapeHtml(reference) + '"><span><strong>' + escapeHtml(reference) + '</strong><small>' + escapeHtml(info.name) + '</small></span><b>' + total + ' cajas</b></button>'; }).join(""); content.addEventListener("click", function (event) { var button = event.target.closest("[data-hu344-result-reference]"); if (!button) return; window.SialMobileUI.closeDialog("hu344-result-reference"); addResultFor(button.dataset.hu344ResultReference); }); window.SialMobileUI.openDialog({ id: "hu344-result-reference", variant: "sheet", title: "Agregar pallet resultado", message: "Elige la referencia del nuevo pallet. Las referencias no se mezclan.", content: content, returnFocus: $("[data-hu344-add-result]"), actions: [{ label: "Cancelar", variant: "secondary" }] }); }
  function removeResult(index) { var target = results[index], totals = referenceTotals(), counts = resultCounts(), minimum = Math.max(1, Math.ceil(Number(totals[target.reference] || 0) / capacity)); if (Number(counts[target.reference] || 0) <= minimum) { showError("La referencia " + target.reference + " requiere al menos " + minimum + " pallet" + (minimum === 1 ? "" : "s") + " resultado.", $("[data-hu344-result-section]")); return; } counts[target.reference] -= 1; resetResults(counts); render(); markDirty(); }

  function renderContext() { if (!selectedPallets.length) { $("[data-hu344-zone]").textContent = "Zona Externa"; $("[data-hu344-context-pallet]").textContent = "pendiente"; $("[data-hu344-context-status]").textContent = "Sin seleccionar"; $("[data-hu344-context-status]").className = "sial-pill warning"; return; } var zones = uniqueZones(); $("[data-hu344-zone]").textContent = zones.length === 1 ? zones[0] : zones.length + " zonas ZE"; $("[data-hu344-context-pallet]").textContent = selectedPallets.length + " seleccionado" + (selectedPallets.length === 1 ? "" : "s"); $("[data-hu344-context-status]").textContent = totalOriginBoxes() + " cajas"; $("[data-hu344-context-status]").className = "sial-pill info"; }
  function renderBases() {
    var list = $("[data-hu344-base-list]"); $("[data-hu344-base-pill]").textContent = selectedPallets.length ? selectedPallets.length + " seleccionado" + (selectedPallets.length === 1 ? "" : "s") : "Sin seleccionar"; $("[data-hu344-base-pill]").className = "sial-pill" + (selectedPallets.length ? " info" : "");
    if (!selectedPallets.length) { list.innerHTML = '<div class="hu344-source-empty"><strong>Sin pallets de origen</strong><span>Selecciona uno o varios pallets para definir la distribución.</span></div>'; setNote("[data-hu344-base-status]", "La selección muestra estado, referencia y cajas de cada pallet.", ""); return; }
    list.innerHTML = selectedPallets.map(function (item, index) { var state = palletState(item), stateClass = palletType(item) === "MIXED" ? " info" : " warning", refs = itemComposition(item).map(function (component) { return component.reference; }).join(" + "); return '<article class="hu344-selected-pallet"><header><span><small>Origen ' + String(index + 1).padStart(2, "0") + '</small><strong>' + escapeHtml(item.sscc) + '</strong></span><button class="sial-chip-action" type="button" data-hu344-remove-base="' + escapeHtml(item.sscc) + '">Quitar</button></header><div><span class="sial-pill' + stateClass + '">' + state + '</span><b>' + escapeHtml(refs) + '</b><small>' + escapeHtml(item.farmCode + " · " + item.farmName) + '</small><strong>' + Number(item.boxes) + ' cajas</strong></div></article>'; }).join(""); setNote("[data-hu344-base-status]", totalOriginBoxes() + " cajas disponibles para redistribuir por referencia.", "success");
  }
  function renderBalance() { var origin = totalOriginBoxes(), assigned = totalResultBoxes(), pending = origin - assigned, totals = referenceTotals(); $("[data-hu344-selected-boxes]").textContent = origin; $("[data-hu344-remaining-boxes]").textContent = Math.abs(pending); $("[data-hu344-capacity-pill]").textContent = assigned + " asignadas"; var bar = $("[data-hu344-capacity-bar]"), percent = origin ? Math.min(100, Math.round((assigned / origin) * 100)) : 0; bar.style.width = percent + "%"; bar.classList.toggle("is-full", origin > 0 && pending === 0); $("[data-hu344-composition-lines]").innerHTML = Object.keys(totals).length ? Object.keys(totals).map(function (code) { var info = referenceInfo(code); return '<div><span><strong>' + escapeHtml(code) + '</strong><small>' + escapeHtml(info.name) + '</small></span><b>' + totals[code] + ' cajas</b></div>'; }).join("") : '<div class="hu344-lineage-empty">La composición aparecerá al seleccionar pallets.</div>'; if (!origin) setNote("[data-hu344-balance-status]", "Selecciona pallets de origen para iniciar la distribución.", ""); else if (pending > 0) setNote("[data-hu344-balance-status]", "Faltan " + pending + " cajas por asignar a los resultados.", "warning"); else if (pending < 0) setNote("[data-hu344-balance-status]", "Sobran " + Math.abs(pending) + " cajas en los resultados.", "error"); else setNote("[data-hu344-balance-status]", "Conciliación completa: todas las cajas tienen un resultado.", "success"); }
  function renderResults() {
    var list = $("[data-hu344-result-list]"), plans = allocationPlan(), counts = resultCounts(), totals = referenceTotals(); $("[data-hu344-result-count]").textContent = results.length + " resultado" + (results.length === 1 ? "" : "s"); $("[data-hu344-add-result]").disabled = !selectedPallets.length || results.length >= totalOriginBoxes();
    if (!results.length) { list.innerHTML = '<div class="hu344-source-empty"><strong>Sin pallets resultado</strong><span>Selecciona los pallets de origen para crear la distribución.</span></div>'; return; }
    list.innerHTML = plans.map(function (item, index) { var state = Number(item.boxes) >= capacity ? "Completo" : "Incompleto", minimum = Math.max(1, Math.ceil(Number(totals[item.reference] || 0) / capacity)), validation = item.sscc ? validateResultSscc(item.sscc, index) : { ok: false, message: "SSCC pendiente" }; return '<article class="hu344-result-card" data-hu344-result-card="' + index + '"><header><span><small>Resultado ' + String(index + 1).padStart(2, "0") + ' · ' + escapeHtml(item.reference) + '</small><strong>' + state + '</strong></span>' + (Number(counts[item.reference] || 0) > minimum ? '<button class="sial-chip-action" type="button" data-hu344-remove-result="' + index + '">Quitar</button>' : '') + '</header><label class="sial-field"><span class="sial-label">Nuevo SSCC</span><input class="sial-input-wrap sial-input" inputmode="numeric" maxlength="18" placeholder="Escanea o digita el SSCC" value="' + escapeHtml(item.sscc) + '" data-hu344-result-sscc="' + index + '"></label><button class="sial-btn sial-btn-secondary sial-btn-full" type="button" data-hu344-scan-result="' + index + '">Escanear SSCC</button><label class="sial-field"><span class="sial-label">Cajas del resultado</span><input class="sial-input-wrap sial-input" type="number" inputmode="numeric" min="1" max="48" value="' + Number(item.boxes) + '" data-hu344-result-boxes="' + index + '"></label><div class="hu344-result-composition"><span>' + escapeHtml(item.reference) + '</span><b>' + Number(item.boxes) + ' cajas</b></div><p class="sial-field-note ' + (validation.ok ? 'success' : '') + '">' + escapeHtml(validation.message) + '</p></article>'; }).join("");
  }
  function renderProgress() { var first = $("[data-hu344-step='context']"), second = $("[data-hu344-step='sources']"), third = $("[data-hu344-step='result']"); [first, second, third].forEach(function (node) { node.className = ""; }); if (!selectedPallets.length) first.classList.add("is-active"); else { first.classList.add("is-complete"); if (!results.length || totalOriginBoxes() !== totalResultBoxes()) second.classList.add("is-active"); else { second.classList.add("is-complete"); third.classList.add(results.every(function (item, index) { return validateResultSscc(item.sscc, index).ok; }) ? "is-complete" : "is-active"); } } }
  function renderSummary() {
    var plans = allocationPlan(), totals = referenceTotals(), mixedCount = selectedPallets.filter(function (item) { return palletType(item) === "MIXED"; }).length; $("[data-hu344-preview-sscc]").textContent = results.length ? results.length + " pallet" + (results.length === 1 ? " resultado" : "s resultado") : "Sin resultados"; $("[data-hu344-preview-boxes]").textContent = totalResultBoxes() + " cajas"; $("[data-hu344-preview-farms]").textContent = uniqueFarms().length + " finca" + (uniqueFarms().length === 1 ? "" : "s"); $("[data-hu344-preview-type]").textContent = !selectedPallets.length ? "Sin seleccionar" : selectedPallets.length + " origen" + (selectedPallets.length === 1 ? "" : "es") + (mixedCount ? " · " + mixedCount + " mixto" + (mixedCount === 1 ? "" : "s") : ""); $("[data-hu344-preview-references]").innerHTML = Object.keys(totals).length ? Object.keys(totals).map(function (reference) { var info = referenceInfo(reference); return '<div class="hu591-label-reference-row"><div><strong>' + escapeHtml(reference) + '</strong><span>' + escapeHtml(info.name) + '</span></div><strong>' + totals[reference] + ' cajas</strong></div>'; }).join("") : '<p>Selecciona pallets para construir la composición.</p>';
    var lineage = $("[data-hu344-lineage]"); if (!selectedPallets.length || !plans.length) lineage.innerHTML = '<span>Linaje SSCC</span><div class="hu344-lineage-empty">Selecciona los pallets de origen para construir el linaje.</div>'; else lineage.innerHTML = '<span>Linaje origen → resultado</span><div class="hu344-lineage-batch">' + plans.map(function (result, index) { return '<div class="hu344-lineage-map"><div class="hu344-lineage-origins">' + result.allocations.map(function (allocation) { return '<div class="hu344-lineage-node"><strong>' + escapeHtml(allocation.sourceSscc) + '</strong><small>' + allocation.boxes + ' cajas · ' + escapeHtml(allocation.reference) + '</small></div>'; }).join("") + '</div><div class="hu344-lineage-merge" aria-hidden="true"><i class="hu344-lineage-arrow"></i></div><div class="hu344-lineage-node hu344-lineage-result"><strong>' + escapeHtml(result.sscc || "SSCC pendiente") + '</strong><small>Resultado ' + String(index + 1).padStart(2, "0") + ' · ' + result.boxes + ' cajas</small></div></div>'; }).join("") + '</div>'; renderProgress();
  }
  function render() { renderContext(); renderBases(); renderBalance(); renderResults(); renderSummary(); }

  function validateDraft() {
    if (!selectedPallets.length) return { message: "Selecciona al menos un pallet de origen.", field: $("[data-hu344-select-base]") };
    if (!results.length) return { message: "Agrega al menos un pallet resultado.", field: $("[data-hu344-result-section]") };
    for (var i = 0; i < results.length; i += 1) if (Number(results[i].boxes) < 1 || Number(results[i].boxes) > capacity) return { message: "Cada pallet resultado debe contener entre 1 y " + capacity + " cajas.", field: $('[data-hu344-result-boxes="' + i + '"]') };
    if (totalOriginBoxes() !== totalResultBoxes()) return { message: "Las cajas de origen y resultado deben coincidir exactamente.", field: $("[data-hu344-balance-section]") };
    var totals = referenceTotals(), assigned = results.reduce(function (values, item) { values[item.reference] = Number(values[item.reference] || 0) + Number(item.boxes || 0); return values; }, {}), mismatch = Object.keys(totals).find(function (reference) { return Number(totals[reference]) !== Number(assigned[reference] || 0); }); if (mismatch) return { message: "Las cajas de la referencia " + mismatch + " deben coincidir entre origen y resultado.", field: $("[data-hu344-result-section]") };
    var plans = allocationPlan(); if (plans.some(function (item) { return resultReferences(item).length !== 1 || resultReferences(item)[0] !== item.reference; })) return { message: "Cada pallet resultado debe conservar una única referencia.", field: $("[data-hu344-result-section]") };
    for (var j = 0; j < results.length; j += 1) { var validation = validateResultSscc(results[j].sscc, j); if (!validation.ok) return { message: "Resultado " + String(j + 1).padStart(2, "0") + ": " + validation.message, field: $('[data-hu344-result-sscc="' + j + '"]') }; } return null;
  }
  function collectRecord() { var now = new Date(), plans = allocationPlan(), totals = referenceTotals(), operationIds = uniqueOperationIds(), zones = uniqueZones(), destinations = Array.from(new Set(operationIds.map(function (id) { var operation = findOperation(id); return operation ? operation.destination : ""; }).filter(Boolean))); return { id: "HU344-" + now.getTime(), hu: "HU344", operation: operationIds.length === 1 ? operationIds[0] : "MULTIPLE", operations: operationIds, zone: zones.length === 1 ? zones[0] : "Múltiples zonas ZE", zones: zones, type: "REASSEMBLY_BY_REFERENCE", status: "REARMADO_MULTIPLE_EN_ZE", sync: "LOCAL_PENDING_SYNC", destination: destinations.length === 1 ? destinations[0] : "Múltiples destinos", destinations: destinations, originCount: selectedPallets.length, resultCount: results.length, boxes: totalOriginBoxes(), references: Object.keys(totals).map(function (reference) { var info = referenceInfo(reference); return { reference: reference, referenceName: info.name, boxes: totals[reference] }; }), sources: selectedPallets.map(function (item) { return { sscc: item.sscc, operationId: item.operationId, zone: item.zone, farmCode: item.farmCode, farmName: item.farmName, palletType: palletType(item), composition: itemComposition(item), availableBoxes: Number(item.boxes), takenBoxes: Number(item.boxes), remainingBoxes: 0, resultStatus: "CONSUMIDO_TOTAL" }; }), results: plans.map(function (item) { return { sscc: normalizeSscc(item.sscc), reference: item.reference, boxes: Number(item.boxes), status: Number(item.boxes) >= capacity ? "PALLET_COMPLETO_EN_ZE" : "PALLET_INCOMPLETO_EN_ZE", references: [item.reference], allocations: item.allocations }; }), observations: $("[data-hu344-observations]").value.trim(), createdAt: now.toISOString(), user: readJson(workflowKey, {}).user || "María Operadora" }; }
  function saveRecord(record) {
    var state = readJson(pageKey, {}); state.records = [record].concat(Array.isArray(state.records) ? state.records : []); state.usedSscc = Array.from(new Set(record.results.map(function (item) { return item.sscc; }).concat(state.usedSscc || []))); var previous = Array.isArray(state.inventoryAdjustments) ? state.inventoryAdjustments : [], changes = record.sources.map(function (item) { return { sscc: item.sscc, remainingBoxes: 0, status: "CONSUMIDO_TOTAL" }; }); state.inventoryAdjustments = previous.filter(function (item) { return !changes.some(function (change) { return change.sscc === item.sscc; }); }).concat(changes); writeJson(pageKey, state);
    var workflow = readJson(workflowKey, {}), infoByCode = {}; record.references.forEach(function (item) { infoByCode[item.reference] = item; }); var ready = record.results.map(function (item) { var first = item.references[0], info = infoByCode[first] || {}; return { sscc: item.sscc, farmCode: "ZE", farmName: record.zone, reference: first, referenceName: info.referenceName || "", references: item.references, boxes: item.boxes, status: item.status, createdAt: record.createdAt, sourceLineage: item.allocations }; }); workflow.readyPallets = ready.concat(Array.isArray(workflow.readyPallets) ? workflow.readyPallets : []); workflow.usedSscc = Array.from(new Set(record.results.map(function (item) { return item.sscc; }).concat(workflow.usedSscc || []))); workflow.crossDockingReassemblies = [record].concat(Array.isArray(workflow.crossDockingReassemblies) ? workflow.crossDockingReassemblies : []); workflow.events = [{ event: "palletsReassembledZE", label: "HU344 · Rearmado múltiple en ZE", detail: record.originCount + " origen(es) → " + record.resultCount + " resultado(s) · " + record.boxes + " cajas", timestamp: new Date().toLocaleString("es-CO"), status: record.status, sync: record.sync }].concat(Array.isArray(workflow.events) ? workflow.events : []); writeJson(workflowKey, workflow);
    var queue = readJson(syncQueueKey, []); if (!Array.isArray(queue)) queue = []; queue.unshift({ id: "sync-" + record.id, hu: "HU344", title: "Rearmado múltiple registrado", subtitle: record.originCount + " origen(es) conciliados en " + record.resultCount + " resultado(s).", operation: record.operation, entity: record.resultCount + " pallets resultado", status: "LOCAL_PENDING_SYNC", evidence: 0, attempts: 0, createdAt: new Date().toLocaleString("es-CO"), localId: record.id, idempotencyKey: record.operation + "_palletsReassembledZE_" + record.id, detail: "Matriz de linaje origen-resultado conservada en el dispositivo.", dependency: "" }); writeJson(syncQueueKey, queue);
  }
  function confirmationContent(record) { var content = document.createElement("div"); content.className = "hu344-confirmation"; content.innerHTML = '<div><span>Orígenes</span><strong>' + record.originCount + ' pallets</strong></div><div><span>Resultados</span><strong>' + record.resultCount + ' pallets</strong></div><div><span>Total</span><strong>' + record.boxes + ' cajas</strong></div><div><span>Relación</span><strong>' + record.originCount + ' → ' + record.resultCount + '</strong></div>'; return content; }
  function complete(record) { saveRecord(record); window.SialMobileUI.clearUnsavedChanges(); window.SialMobileUI.showToast({ type: "success", title: "Rearmado registrado", message: record.originCount + " origen(es) y " + record.resultCount + " resultado(s) quedaron pendientes de sincronización." }); $("[data-hu344-submit]").disabled = true; $("[data-hu344-submit]").textContent = "Rearmado registrado"; $all("input, textarea, select, button", $("[data-hu344-form]")).forEach(function (control) { if (!control.matches("[data-hu344-submit]")) control.disabled = true; }); window.SialMobileUI.setInlineStatus($("[data-flow-error]"), { type: "success", title: "Pallets listos para sincronizar", message: "La conciliación y el linaje múltiple quedaron guardados en este dispositivo.", reveal: false }); $("[data-hu344-summary]").scrollIntoView({ behavior: "smooth", block: "center" }); }
  function confirm() { var validation = validateDraft(); if (validation) { showError(validation.message, validation.field); return; } var record = collectRecord(); window.SialMobileUI.openDialog({ id: "hu344-confirm-reassembly", type: "warning", branded: true, title: "Confirmar rearmado", message: "Todos los pallets de origen quedarán relacionados con sus resultados.", content: confirmationContent(record), returnFocus: $("[data-hu344-submit]"), actions: [{ label: "Volver a revisar", variant: "secondary" }, { label: "Confirmar rearmado", onClick: function () { complete(record); } }] }); }
  function wire() {
    hydrateInventoryAdjustments(); render(); $("[data-hu344-select-base]").addEventListener("click", openPalletPicker); $("[data-hu344-base-list]").addEventListener("click", function (event) { var button = event.target.closest("[data-hu344-remove-base]"); if (button) removePallet(button.dataset.hu344RemoveBase); }); $("[data-hu344-add-result]").addEventListener("click", addResult);
    $("[data-hu344-result-list]").addEventListener("click", function (event) { var scan = event.target.closest("[data-hu344-scan-result]"); if (scan) { scanResult(Number(scan.dataset.hu344ScanResult)); return; } var remove = event.target.closest("[data-hu344-remove-result]"); if (remove) removeResult(Number(remove.dataset.hu344RemoveResult)); });
    $("[data-hu344-result-list]").addEventListener("input", function (event) { var index; if (event.target.matches("[data-hu344-result-sscc]")) { index = Number(event.target.dataset.hu344ResultSscc); results[index].sscc = event.target.value.replace(/\D/g, "").slice(0, 18); results[index].scanSource = "TYPED"; renderSummary(); markDirty(); } else if (event.target.matches("[data-hu344-result-boxes]")) { index = Number(event.target.dataset.hu344ResultBoxes); results[index].boxes = Number(event.target.value || 0); renderBalance(); renderSummary(); markDirty(); } }); $("[data-hu344-result-list]").addEventListener("change", function (event) { if (event.target.matches("[data-hu344-result-sscc], [data-hu344-result-boxes]")) render(); }); $("[data-hu344-observations]").addEventListener("input", markDirty); $("[data-hu344-form]").addEventListener("submit", function (event) { event.preventDefault(); confirm(); });
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", wire); else wire();
})();
