(function () {
  "use strict";
  var workflowKey = "sial-mobile-workflow", hu591Key = "sial-mobile-hu591", pageKey = "sial-mobile-hu344", syncQueueKey = "sial-mobile-sync-queue", capacity = 48;
  var operations = [
    { id: "XD-2026-0418", zone: "ZE Puerto Norte", destination: "Puerto Amberes", references: [{ code: "BAN-REF-001", name: "Premium 22XU" }, { code: "BAN-REF-004", name: "Cluster 208" }], pallets: [
      { sscc: "177012345678900019", farmCode: "0435", farmName: "Finca La Bacota", reference: "BAN-REF-001", referenceName: "Premium 22XU", boxes: 30, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900026", farmCode: "0527", farmName: "Finca Santa Isabel", reference: "BAN-REF-001", referenceName: "Premium 22XU", boxes: 18, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900033", farmCode: "0412", farmName: "Finca La Esperanza", reference: "BAN-REF-001", referenceName: "Premium 22XU", boxes: 22, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900071", farmCode: "0435", farmName: "Finca La Bacota", reference: "BAN-REF-004", referenceName: "Cluster 208", boxes: 24, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900088", farmCode: "0527", farmName: "Finca Santa Isabel", boxes: 48, palletType: "MIXED", composition: [{ reference: "BAN-REF-001", referenceName: "Premium 22XU", boxes: 24 }, { reference: "BAN-REF-004", referenceName: "Cluster 208", boxes: 24 }], status: "DISPONIBLE_EN_ZE" }
    ] },
    { id: "XD-2026-0520", zone: "ZE Terminal Sur", destination: "Puerto Róterdam", references: [{ code: "BAN-REF-018", name: "Baby Banana" }, { code: "BAN-REF-022", name: "Orgánico 18KG" }], pallets: [
      { sscc: "177012345678900042", farmCode: "0527", farmName: "Finca Santa Isabel", reference: "BAN-REF-018", referenceName: "Baby Banana", boxes: 28, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900059", farmCode: "0412", farmName: "Finca La Esperanza", reference: "BAN-REF-018", referenceName: "Baby Banana", boxes: 20, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900066", farmCode: "0435", farmName: "Finca La Bacota", reference: "BAN-REF-022", referenceName: "Orgánico 18KG", boxes: 24, palletType: "INCOMPLETE", status: "DISPONIBLE_EN_ZE" },
      { sscc: "177012345678900073", farmCode: "0527", farmName: "Finca Santa Isabel", boxes: 24, palletType: "MIXED", composition: [{ reference: "BAN-REF-018", referenceName: "Baby Banana", boxes: 12 }, { reference: "BAN-REF-022", referenceName: "Orgánico 18KG", boxes: 12 }], status: "DISPONIBLE_EN_ZE" }
    ] }
  ];
  var selectedOperation = null, selectedPallets = [], results = [], resultSequence = 0;
  function $(selector, root) { return (root || document).querySelector(selector); }
  function $all(selector, root) { return Array.from((root || document).querySelectorAll(selector)); }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function escapeHtml(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (char) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]; }); }
  function readJson(key, fallback) { try { return JSON.parse(localStorage.getItem(key) || "") || fallback; } catch (_) { return fallback; } }
  function writeJson(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
  function normalizeSscc(value) { if (window.SialMobileUI && typeof window.SialMobileUI.normalizeSscc === "function") return window.SialMobileUI.normalizeSscc(value); var digits = String(value || "").replace(/\D/g, ""); return digits.length === 20 && digits.slice(0, 2) === "00" ? digits.slice(2) : digits; }
  function checkDigit(body) { var sum = 0; for (var i = body.length - 1, weight = 3; i >= 0; i -= 1, weight = weight === 3 ? 1 : 3) sum += Number(body.charAt(i)) * weight; return String((10 - (sum % 10)) % 10); }
  function setNote(selector, message, type) { var node = $(selector); if (!node) return; node.textContent = message; node.className = "sial-field-note" + (type ? " " + type : ""); }
  function clearError(field) { if (field) { field.removeAttribute("aria-invalid"); field.classList.remove("sial-error-target"); } var error = $("[data-flow-error]"); if (error && window.SialMobileUI && typeof window.SialMobileUI.clearInlineStatus === "function") window.SialMobileUI.clearInlineStatus(error); else if (error) error.hidden = true; }
  function showError(message, field) { var error = $("[data-flow-error]"); if (window.SialMobileUI && typeof window.SialMobileUI.setInlineStatus === "function") window.SialMobileUI.setInlineStatus(error, { type: "error", title: "Revisa la conciliación", message: message, form: error.closest("form"), field: field }); else { error.hidden = false; error.textContent = message; (field || error).scrollIntoView({ behavior: "smooth", block: "center" }); } }
  function markDirty() { if (window.SialMobileUI && typeof window.SialMobileUI.markUnsavedChanges === "function") window.SialMobileUI.markUnsavedChanges("hu344"); }
  function allPallets() { return operations.reduce(function (list, operation) { return list.concat(operation.pallets.map(function (item) { return Object.assign({ operationId: operation.id, zone: operation.zone }, item); })); }, []); }
  function findOperation(id) { return operations.find(function (item) { return item.id === id; }) || null; }
  function palletType(item) { return item.palletType === "MIXED" || (Array.isArray(item.composition) && item.composition.length > 1) ? "MIXED" : "INCOMPLETE"; }
  function palletState(item) { return palletType(item) === "MIXED" ? "Mixto" : "Incompleto"; }
  function itemComposition(item) { return Array.isArray(item.composition) && item.composition.length ? item.composition : [{ reference: item.reference, referenceName: item.referenceName || "", boxes: Number(item.boxes || 0) }]; }
  function initializeTakenComposition(item) { if (!Array.isArray(item.takenComposition)) item.takenComposition = itemComposition(item).map(function (component) { return { reference: component.reference, referenceName: component.referenceName || "", boxes: Number(component.boxes || 0), selected: true }; }); return item; }
  function selectedComposition(item) { initializeTakenComposition(item); return item.takenComposition.map(function (component) { var available = itemComposition(item).find(function (source) { return source.reference === component.reference; }), maximum = Number(available ? available.boxes : 0), selected = component.selected !== false; return { reference: component.reference, referenceName: component.referenceName || (available ? available.referenceName : ""), boxes: selected ? Math.max(0, Math.min(maximum, Number(component.boxes || 0))) : 0, selected: selected }; }); }
  function totalTakenFromPallet(item) { return selectedComposition(item).reduce(function (sum, component) { return sum + Number(component.boxes || 0); }, 0); }
  function totalOriginBoxes() { return selectedPallets.reduce(function (sum, item) { return sum + totalTakenFromPallet(item); }, 0); }
  function totalResultBoxes() { return results.reduce(function (sum, item) { return sum + Number(item.boxes || 0); }, 0); }
  function uniqueFarms() { return Array.from(new Set(selectedPallets.map(function (item) { return item.farmCode; }))); }
  function uniqueOperationIds() { return Array.from(new Set(selectedPallets.map(function (item) { return item.operationId; }).filter(Boolean))); }
  function uniqueZones() { return Array.from(new Set(selectedPallets.map(function (item) { return item.zone; }).filter(Boolean))); }
  function referenceInfo(code) { for (var p = 0; p < selectedPallets.length; p += 1) { var component = itemComposition(selectedPallets[p]).find(function (item) { return item.reference === code; }); if (component) return { code: code, name: component.referenceName || "" }; } for (var i = 0; i < operations.length; i += 1) { var match = operations[i].references.find(function (item) { return item.code === code; }); if (match) return match; } return { code: code, name: "" }; }
  function referenceTotals() { return selectedPallets.reduce(function (totals, item) { selectedComposition(item).forEach(function (component) { if (Number(component.boxes) > 0) totals[component.reference] = Number(totals[component.reference] || 0) + Number(component.boxes); }); return totals; }, {}); }
  function hydrateInventoryAdjustments() { var state = readJson(pageKey, {}), adjustments = Array.isArray(state.inventoryAdjustments) ? state.inventoryAdjustments : []; operations.forEach(function (operation) { operation.pallets.forEach(function (item) { var adjustment = adjustments.find(function (candidate) { return candidate.sscc === item.sscc; }); if (adjustment) { if (Array.isArray(adjustment.remainingComposition)) { item.composition = clone(adjustment.remainingComposition); if (item.composition.length === 1) { item.reference = item.composition[0].reference; item.referenceName = item.composition[0].referenceName; } } item.boxes = Number(adjustment.remainingBoxes || 0); item.status = item.boxes > 0 ? "DISPONIBLE_EN_ZE" : adjustment.status; } }); }); }
  function availablePallets() { return allPallets().filter(function (item) { return item.status === "DISPONIBLE_EN_ZE" && Number(item.boxes) > 0; }); }
  function resetResults(_, preserve) { var totals = referenceTotals(), total = totalOriginBoxes(), previous = preserve === false ? null : results[0]; results = total > 0 ? [{ id: previous ? previous.id : "result-" + (++resultSequence), sscc: previous ? previous.sscc : "", boxes: total, composition: Object.keys(totals).map(function (reference) { return { reference: reference, boxes: Number(totals[reference]) }; }), scanSource: previous ? previous.scanSource : "TYPED" }] : []; }
  function reconcileAfterSelection() { selectedOperation = selectedPallets.length ? findOperation(selectedPallets[0].operationId) : null; resetResults({}, false); clearError(); render(); markDirty(); }

  function openPalletPicker() {
    var draft = selectedPallets.map(function (item) { return item.sscc; }), query = "", filter = "ALL", content = document.createElement("div"); content.className = "hu344-picker-shell";
    content.innerHTML = '<div class="hu344-picker-tools"><label class="hu344-picker-search"><svg class="sial-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg><input type="search" inputmode="search" autocomplete="off" placeholder="Buscar SSCC, referencia o finca" aria-label="Buscar pallets" data-hu344-picker-search></label><button class="sial-btn sial-btn-primary hu344-picker-scan" type="button" data-hu344-picker-scan aria-label="Escanear SSCC de pallet"><svg class="sial-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4M7 12h10"></path></svg><span>Escanear</span></button></div><div class="hu344-picker-filters" role="group" aria-label="Filtrar pallets por tipo"><button class="is-selected" type="button" aria-pressed="true" data-hu344-picker-filter="ALL">Todos</button><button type="button" aria-pressed="false" data-hu344-picker-filter="INCOMPLETE">Incompletos</button><button type="button" aria-pressed="false" data-hu344-picker-filter="MIXED">Mixtos</button></div><p class="hu344-picker-status" role="status" aria-live="polite" data-hu344-picker-status></p><div class="hu344-base-picker" data-hu344-picker-list></div>';
    var search = $("[data-hu344-picker-search]", content), list = $("[data-hu344-picker-list]", content), status = $("[data-hu344-picker-status]", content);
    function searchableText(item) { return [item.sscc, item.farmCode, item.farmName, item.zone, palletState(item)].concat(itemComposition(item).map(function (component) { return component.reference + " " + component.referenceName; })).join(" ").toLocaleLowerCase("es"); }
    function referenceLabel(item) { var references = itemComposition(item).map(function (component) { return component.reference; }); return references.length === 1 ? references[0] : references.length + " referencias"; }
    function draw() {
      var term = query.trim().toLocaleLowerCase("es"), available = availablePallets(), filtered = available.filter(function (item) { return filter === "ALL" || palletType(item) === filter; }); if (term) filtered = filtered.filter(function (item) { return searchableText(item).indexOf(term) >= 0; });
      status.textContent = term ? filtered.length + " coincidencia" + (filtered.length === 1 ? "" : "s") + " · " + draft.length + " seleccionado" + (draft.length === 1 ? "" : "s") : filtered.length + " pallet" + (filtered.length === 1 ? "" : "s") + (filter === "INCOMPLETE" ? " incompletos" : filter === "MIXED" ? " mixtos" : " disponibles") + " · " + draft.length + " seleccionado" + (draft.length === 1 ? "" : "s");
      list.innerHTML = filtered.length ? filtered.map(function (item) { var selected = draft.indexOf(item.sscc) >= 0, state = palletState(item), stateClass = palletType(item) === "MIXED" ? " info" : " warning"; return '<button class="hu344-picker-pallet' + (selected ? ' is-selected' : '') + '" type="button" aria-pressed="' + selected + '" data-hu344-picker-option="' + escapeHtml(item.sscc) + '"><span class="hu344-picker-content"><span class="hu344-picker-heading"><strong>' + escapeHtml(item.sscc) + '</strong><i class="sial-pill' + stateClass + '">' + state + '</i></span><span class="hu344-picker-details"><b>' + escapeHtml(referenceLabel(item)) + '</b><small>' + Number(item.boxes) + ' cajas</small></span><small class="hu344-picker-farm">' + escapeHtml(item.farmCode + " · " + item.farmName) + '</small></span><i class="hu344-picker-check" aria-hidden="true">' + (selected ? '✓' : '') + '</i></button>'; }).join("") : '<div class="hu344-picker-empty"><strong>Sin coincidencias</strong><span>Prueba con otro tipo, SSCC, referencia o finca.</span></div>';
    }
    function scanBasePallet() {
      var available = availablePallets();
      window.SialMobileUI.openBarcodeScanner({ title: "Escanear pallet base", eyebrow: "HU344 · Selección de origen", normalize: normalizeSscc, validate: function (value) { var code = normalizeSscc(value), match = available.find(function (item) { return item.sscc === code; }); return match ? { ok: true, message: "Pallet disponible para seleccionar." } : { ok: false, message: "El SSCC no corresponde a un pallet disponible en ZE." }; }, onDetected: function (value) { var code = normalizeSscc(value), match = available.find(function (item) { return item.sscc === code; }); if (draft.indexOf(code) < 0) draft.push(code); query = ""; search.value = ""; filter = match ? palletType(match) : "ALL"; $all("[data-hu344-picker-filter]", content).forEach(function (button) { var selected = button.dataset.hu344PickerFilter === filter; button.classList.toggle("is-selected", selected); button.setAttribute("aria-pressed", String(selected)); }); draw(); status.textContent = "Pallet " + code + " seleccionado por escaneo."; } });
    }
    search.addEventListener("input", function () { query = search.value; draw(); });
    content.addEventListener("click", function (event) { var filterButton = event.target.closest("[data-hu344-picker-filter]"); if (filterButton) { filter = filterButton.dataset.hu344PickerFilter; $all("[data-hu344-picker-filter]", content).forEach(function (button) { var selected = button === filterButton; button.classList.toggle("is-selected", selected); button.setAttribute("aria-pressed", String(selected)); }); draw(); return; } var scan = event.target.closest("[data-hu344-picker-scan]"); if (scan) { scanBasePallet(); return; } var button = event.target.closest("[data-hu344-picker-option]"); if (!button) return; var sscc = button.dataset.hu344PickerOption, index = draft.indexOf(sscc); if (index >= 0) draft.splice(index, 1); else draft.push(sscc); draw(); }); draw();
    window.SialMobileUI.openDialog({ id: "hu344-pallet-picker", variant: "sheet", title: "Seleccionar pallets", message: "Elige uno o varios pallets base. Cada pallet conserva los datos de su operación.", content: content, returnFocus: $("[data-hu344-select-base]"), actions: [{ label: "Cancelar", variant: "secondary" }, { label: "Usar selección", onClick: function () { selectedPallets = draft.map(function (sscc) { var current = selectedPallets.find(function (item) { return item.sscc === sscc; }), source = current || clone(allPallets().find(function (item) { return item.sscc === sscc; })); return source ? initializeTakenComposition(source) : null; }).filter(Boolean); reconcileAfterSelection(); } }] });
  }
  function removePallet(sscc) { selectedPallets = selectedPallets.filter(function (item) { return item.sscc !== sscc; }); reconcileAfterSelection(); }
  function allocationPlan() {
    var allocations = []; selectedPallets.forEach(function (item) { selectedComposition(item).forEach(function (component) { if (Number(component.boxes) > 0) allocations.push({ sourceSscc: item.sscc, operationId: item.operationId, zone: item.zone, farmCode: item.farmCode, farmName: item.farmName, reference: component.reference, boxes: Number(component.boxes) }); }); });
    return results.map(function (result) { return Object.assign({}, result, { allocations: allocations.slice() }); });
  }
  function resultReferences(result) { return Array.from(new Set((result.allocations || []).map(function (item) { return item.reference; }))); }
  function allUsedSscc() { var hu591 = readJson(hu591Key, {}), workflow = readJson(workflowKey, {}), hu344 = readJson(pageKey, {}), ready = [].concat(hu591.readyPallets || [], workflow.readyPallets || []); return new Set([].concat(allPallets().map(function (item) { return item.sscc; }), hu591.usedSscc || [], workflow.usedSscc || [], hu344.usedSscc || [], ready.map(function (item) { return item.sscc; })).filter(Boolean)); }
  function validateResultSscc(value) { var code = normalizeSscc(value); if (code.length !== 18) return { ok: false, message: "El SSCC debe contener 18 dígitos." }; if (checkDigit(code.slice(0, 17)) !== code.slice(17)) return { ok: false, message: "El dígito de control no es válido." }; if (allUsedSscc().has(code)) return { ok: false, message: "Este SSCC ya pertenece a otro pallet." }; return { ok: true, message: "SSCC válido y disponible." }; }
  function scanResult(index) { window.SialMobileUI.openBarcodeScanner({ title: "Escanear pallet resultado", eyebrow: "Pallet resultado único", normalize: normalizeSscc, validate: validateResultSscc, onDetected: function (value) { results[index].sscc = normalizeSscc(value); results[index].scanSource = "SCANNED"; render(); markDirty(); } }); }

  function renderContext() { if (!selectedPallets.length) { $("[data-hu344-zone]").textContent = "Zona Externa"; $("[data-hu344-context-pallet]").textContent = "Sin pallets"; $("[data-hu344-context-status]").textContent = "Sin seleccionar"; $("[data-hu344-context-status]").className = "sial-pill warning"; return; } var zones = uniqueZones(); $("[data-hu344-zone]").textContent = zones.length === 1 ? zones[0] : zones.length + " zonas ZE"; $("[data-hu344-context-pallet]").textContent = selectedPallets.length + " pallet" + (selectedPallets.length === 1 ? " seleccionado" : "s seleccionados"); $("[data-hu344-context-status]").textContent = totalOriginBoxes() + " cajas"; $("[data-hu344-context-status]").className = "sial-pill info"; }
  function renderBases() {
    var list = $("[data-hu344-base-list]"); $("[data-hu344-base-pill]").textContent = selectedPallets.length ? selectedPallets.length + " seleccionado" + (selectedPallets.length === 1 ? "" : "s") : "Sin seleccionar"; $("[data-hu344-base-pill]").className = "sial-pill" + (selectedPallets.length ? " info" : "");
    if (!selectedPallets.length) { list.innerHTML = '<div class="hu344-source-empty"><strong>Sin pallets de origen</strong><span>Selecciona uno o varios pallets para definir la distribución.</span></div>'; setNote("[data-hu344-base-status]", "Después de seleccionar, define las cajas que tomarás de cada pallet.", ""); return; }
    list.innerHTML = selectedPallets.map(function (item, index) {
      var state = palletState(item), stateClass = palletType(item) === "MIXED" ? " info" : " warning", available = itemComposition(item), taken = selectedComposition(item), takenTotal = totalTakenFromPallet(item), remaining = Number(item.boxes) - takenTotal;
      var controls = available.map(function (component) { var chosen = taken.find(function (entry) { return entry.reference === component.reference; }), selected = chosen ? chosen.selected !== false : true, value = Number(chosen ? chosen.boxes : 0), selector = palletType(item) === "MIXED" ? '<input type="checkbox" ' + (selected ? 'checked ' : '') + 'aria-label="Incluir ' + escapeHtml(component.reference) + '" data-hu344-source-reference-toggle="' + index + '" data-hu344-source-reference="' + escapeHtml(component.reference) + '"><i aria-hidden="true">✓</i>' : ''; return '<div class="hu344-origin-allocation' + (selected ? '' : ' is-unselected') + '"><label class="hu344-origin-reference">' + selector + '<span><b>' + escapeHtml(component.reference) + '</b><small>' + escapeHtml(component.referenceName || "") + '</small></span></label><label class="hu344-origin-input"><input type="number" inputmode="numeric" min="0" max="' + Number(component.boxes) + '" value="' + value + '" ' + (selected ? '' : 'disabled ') + 'aria-label="Cajas a tomar de ' + escapeHtml(component.reference) + '" data-hu344-source-boxes="' + index + '" data-hu344-source-reference="' + escapeHtml(component.reference) + '"><small>de ' + Number(component.boxes) + '</small></label></div>'; }).join("");
      return '<article class="hu344-selected-pallet" data-hu344-source-card="' + index + '"><header><span><small>Origen ' + String(index + 1).padStart(2, "0") + '</small><strong>' + escapeHtml(item.sscc) + '</strong></span><button class="sial-chip-action" type="button" data-hu344-remove-base="' + escapeHtml(item.sscc) + '">Quitar</button></header><div class="hu344-origin-overview"><span class="sial-pill' + stateClass + '">' + state + '</span><small>' + escapeHtml(item.farmCode + " · " + item.farmName) + '</small><strong><span data-hu344-source-taken="' + index + '">' + takenTotal + '</span> de ' + Number(item.boxes) + ' cajas</strong></div><div class="hu344-origin-boxes"><div class="hu344-origin-boxes-head"><span>' + (palletType(item) === "MIXED" ? "Referencias y cajas a tomar" : "Cajas a tomar") + '</span><small><b data-hu344-source-remaining="' + index + '">' + remaining + '</b> quedan en origen</small></div>' + controls + '</div></article>';
    }).join(""); setNote("[data-hu344-base-status]", totalOriginBoxes() + " cajas seleccionadas para el nuevo armado.", "success");
  }
  function renderBalance() { var origin = totalOriginBoxes(), totals = referenceTotals(), available = Math.max(0, capacity - origin), exceeded = Math.max(0, origin - capacity); $("[data-hu344-selected-boxes]").textContent = origin; $("[data-hu344-remaining-boxes]").textContent = available; $("[data-hu344-capacity-pill]").textContent = origin + " / " + capacity + " cajas"; var bar = $("[data-hu344-capacity-bar]"), percent = origin ? Math.min(100, Math.round((origin / capacity) * 100)) : 0; bar.style.width = percent + "%"; bar.classList.toggle("is-full", origin > 0 && origin <= capacity); $("[data-hu344-composition-lines]").innerHTML = Object.keys(totals).length ? Object.keys(totals).map(function (code) { var info = referenceInfo(code); return '<div><span><strong>' + escapeHtml(code) + '</strong><small>' + escapeHtml(info.name) + '</small></span><b>' + totals[code] + ' cajas</b></div>'; }).join("") : '<div class="hu344-lineage-empty">La composición aparecerá al seleccionar pallets.</div>'; if (!origin) setNote("[data-hu344-balance-status]", "Selecciona pallets de origen para construir el pallet resultado.", ""); else if (exceeded) setNote("[data-hu344-balance-status]", "Reduce " + exceeded + " cajas: el único pallet resultado admite máximo " + capacity + ".", "error"); else setNote("[data-hu344-balance-status]", "Composición lista para un único pallet resultado.", "success"); }
  function renderResults() {
    var list = $("[data-hu344-result-list]"), plans = allocationPlan(), totals = referenceTotals(); $("[data-hu344-result-count]").textContent = results.length ? "1 resultado" : "Pendiente";
    if (!results.length) { list.innerHTML = '<div class="hu344-source-empty"><strong>Resultado pendiente</strong><span>Selecciona cajas de los pallets de origen para construirlo.</span></div>'; return; }
    list.innerHTML = plans.map(function (item, index) { var references = Object.keys(totals), state = Number(item.boxes) > capacity ? "Excede capacidad" : Number(item.boxes) === capacity ? "Completo" : "Incompleto", validation = item.sscc ? validateResultSscc(item.sscc, index) : { ok: false, message: "SSCC pendiente" }, composition = references.map(function (reference) { return '<div><span>' + escapeHtml(reference) + '</span><b>' + Number(totals[reference]) + ' cajas</b></div>'; }).join(""); return '<article class="hu344-result-card" data-hu344-result-card="' + index + '"><header><span><small>Pallet resultado único · ' + references.length + ' referencia' + (references.length === 1 ? '' : 's') + '</small><strong>' + state + '</strong></span></header><label class="sial-field"><span class="sial-label">Nuevo SSCC</span><input class="sial-input-wrap sial-input" inputmode="numeric" maxlength="18" placeholder="Escanea o digita el SSCC" value="' + escapeHtml(item.sscc) + '" data-hu344-result-sscc="' + index + '"></label><button class="sial-btn sial-btn-secondary sial-btn-full" type="button" data-hu344-scan-result="' + index + '">Escanear SSCC</button><div class="hu344-result-total"><span>Total del pallet</span><strong>' + Number(item.boxes) + ' de ' + capacity + ' cajas</strong></div><div class="hu344-result-reference-list">' + composition + '</div><p class="sial-field-note ' + (validation.ok ? 'success' : '') + '">' + escapeHtml(validation.message) + '</p></article>'; }).join("");
  }
  function renderProgress() { var first = $("[data-hu344-step='context']"), second = $("[data-hu344-step='sources']"), third = $("[data-hu344-step='result']"); [first, second, third].forEach(function (node) { node.className = ""; }); if (!selectedPallets.length) first.classList.add("is-active"); else { first.classList.add("is-complete"); if (!results.length || totalOriginBoxes() > capacity) second.classList.add("is-active"); else { second.classList.add("is-complete"); third.classList.add(validateResultSscc(results[0].sscc, 0).ok ? "is-complete" : "is-active"); } } }
  function renderSummary() {
    var plans = allocationPlan(), totals = referenceTotals(), mixedCount = selectedPallets.filter(function (item) { return palletType(item) === "MIXED"; }).length; $("[data-hu344-preview-sscc]").textContent = results.length ? "1 pallet resultado" : "Sin resultado"; $("[data-hu344-preview-boxes]").textContent = totalResultBoxes() + " cajas"; $("[data-hu344-preview-farms]").textContent = uniqueFarms().length + " finca" + (uniqueFarms().length === 1 ? "" : "s"); $("[data-hu344-preview-type]").textContent = !selectedPallets.length ? "Sin seleccionar" : selectedPallets.length + " origen" + (selectedPallets.length === 1 ? "" : "es") + (mixedCount ? " · " + mixedCount + " mixto" + (mixedCount === 1 ? "" : "s") : ""); $("[data-hu344-preview-references]").innerHTML = Object.keys(totals).length ? Object.keys(totals).map(function (reference) { var info = referenceInfo(reference); return '<div class="hu591-label-reference-row"><div><strong>' + escapeHtml(reference) + '</strong><span>' + escapeHtml(info.name) + '</span></div><strong>' + totals[reference] + ' cajas</strong></div>'; }).join("") : '<p>Selecciona pallets para construir la composición.</p>';
    var lineage = $("[data-hu344-lineage]"); if (!selectedPallets.length || !plans.length) lineage.innerHTML = '<span>Linaje SSCC</span><div class="hu344-lineage-empty">Selecciona los pallets de origen para construir el linaje.</div>'; else lineage.innerHTML = '<span>Linaje origen → resultado</span><div class="hu344-lineage-batch">' + plans.map(function (result) { return '<div class="hu344-lineage-map"><div class="hu344-lineage-origins">' + result.allocations.map(function (allocation) { return '<div class="hu344-lineage-node"><strong>' + escapeHtml(allocation.sourceSscc) + '</strong><small>' + allocation.boxes + ' cajas · ' + escapeHtml(allocation.reference) + '</small></div>'; }).join("") + '</div><div class="hu344-lineage-merge" aria-hidden="true"><i class="hu344-lineage-arrow"></i></div><div class="hu344-lineage-node hu344-lineage-result"><strong>' + escapeHtml(result.sscc || "SSCC pendiente") + '</strong><small>Resultado único · ' + result.boxes + ' cajas</small></div></div>'; }).join("") + '</div>'; renderProgress();
  }
  function render() { renderContext(); renderBases(); renderBalance(); renderResults(); renderSummary(); }

  function validateDraft() {
    if (!selectedPallets.length) return { message: "Selecciona al menos un pallet de origen.", field: $("[data-hu344-select-base]") };
    var emptySource = selectedPallets.findIndex(function (item) { return totalTakenFromPallet(item) < 1; }); if (emptySource >= 0) return { message: palletType(selectedPallets[emptySource]) === "MIXED" ? "Selecciona al menos una referencia y sus cajas en el origen " + String(emptySource + 1).padStart(2, "0") + "." : "Indica cuántas cajas tomarás del origen " + String(emptySource + 1).padStart(2, "0") + ".", field: $('[data-hu344-source-card="' + emptySource + '"]') };
    if (results.length !== 1) return { message: "El rearmado debe generar exactamente un pallet resultado.", field: $("[data-hu344-result-section]") };
    if (Number(results[0].boxes) < 1 || Number(results[0].boxes) > capacity) return { message: "Reduce la selección: el único pallet resultado debe contener entre 1 y " + capacity + " cajas.", field: $("[data-hu344-balance-section]") };
    if (totalOriginBoxes() !== totalResultBoxes()) return { message: "Las cajas de origen y resultado deben coincidir exactamente.", field: $("[data-hu344-balance-section]") };
    var totals = referenceTotals(), plans = allocationPlan(), plannedReferences = resultReferences(plans[0]); if (Object.keys(totals).some(function (reference) { return plannedReferences.indexOf(reference) < 0; })) return { message: "Todas las referencias seleccionadas deben quedar relacionadas con el pallet resultado.", field: $("[data-hu344-result-section]") };
    for (var j = 0; j < results.length; j += 1) { var validation = validateResultSscc(results[j].sscc, j); if (!validation.ok) return { message: "Resultado " + String(j + 1).padStart(2, "0") + ": " + validation.message, field: $('[data-hu344-result-sscc="' + j + '"]') }; } return null;
  }
  function collectRecord() { var now = new Date(), plans = allocationPlan(), totals = referenceTotals(), referenceCodes = Object.keys(totals), operationIds = uniqueOperationIds(), zones = uniqueZones(), destinations = Array.from(new Set(operationIds.map(function (id) { var operation = findOperation(id); return operation ? operation.destination : ""; }).filter(Boolean))); return { id: "HU344-" + now.getTime(), hu: "HU344", operation: operationIds.length === 1 ? operationIds[0] : "MULTIPLE", operations: operationIds, zone: zones.length === 1 ? zones[0] : "Múltiples zonas ZE", zones: zones, type: "REASSEMBLY_SINGLE_RESULT", status: "REARMADO_EN_ZE", sync: "LOCAL_PENDING_SYNC", destination: destinations.length === 1 ? destinations[0] : "Múltiples destinos", destinations: destinations, originCount: selectedPallets.length, resultCount: 1, boxes: totalOriginBoxes(), references: referenceCodes.map(function (reference) { var info = referenceInfo(reference); return { reference: reference, referenceName: info.name, boxes: totals[reference] }; }), sources: selectedPallets.map(function (item) { var composition = itemComposition(item), takenComposition = selectedComposition(item), remainingComposition = composition.map(function (component) { var taken = takenComposition.find(function (entry) { return entry.reference === component.reference; }); return { reference: component.reference, referenceName: component.referenceName || "", boxes: Math.max(0, Number(component.boxes) - Number(taken ? taken.boxes : 0)) }; }).filter(function (component) { return component.boxes > 0; }), takenBoxes = totalTakenFromPallet(item), remainingBoxes = Number(item.boxes) - takenBoxes; return { sscc: item.sscc, operationId: item.operationId, zone: item.zone, farmCode: item.farmCode, farmName: item.farmName, palletType: palletType(item), composition: composition, takenComposition: takenComposition, remainingComposition: remainingComposition, availableBoxes: Number(item.boxes), takenBoxes: takenBoxes, remainingBoxes: remainingBoxes, resultStatus: remainingBoxes > 0 ? "PALLET_INCOMPLETO_EN_ZE" : "CONSUMIDO_TOTAL" }; }), results: plans.map(function (item) { return { sscc: normalizeSscc(item.sscc), reference: referenceCodes.length === 1 ? referenceCodes[0] : "MIXED", boxes: Number(item.boxes), status: Number(item.boxes) === capacity ? "PALLET_COMPLETO_EN_ZE" : "PALLET_INCOMPLETO_EN_ZE", references: referenceCodes, composition: item.composition, allocations: item.allocations }; }), observations: $("[data-hu344-observations]").value.trim(), createdAt: now.toISOString(), user: readJson(workflowKey, {}).user || "María Operadora" }; }
  function saveRecord(record) {
    var state = readJson(pageKey, {}); state.records = [record].concat(Array.isArray(state.records) ? state.records : []); state.usedSscc = Array.from(new Set(record.results.map(function (item) { return item.sscc; }).concat(state.usedSscc || []))); var previous = Array.isArray(state.inventoryAdjustments) ? state.inventoryAdjustments : [], changes = record.sources.map(function (item) { return { sscc: item.sscc, remainingBoxes: item.remainingBoxes, remainingComposition: item.remainingComposition, status: item.resultStatus }; }); state.inventoryAdjustments = previous.filter(function (item) { return !changes.some(function (change) { return change.sscc === item.sscc; }); }).concat(changes); writeJson(pageKey, state);
    var workflow = readJson(workflowKey, {}), infoByCode = {}; record.references.forEach(function (item) { infoByCode[item.reference] = item; }); var ready = record.results.map(function (item) { var first = item.references[0], info = infoByCode[first] || {}; return { sscc: item.sscc, farmCode: "ZE", farmName: record.zone, reference: first, referenceName: info.referenceName || "", references: item.references, composition: item.composition, boxes: item.boxes, status: item.status, createdAt: record.createdAt, sourceLineage: item.allocations }; }); workflow.readyPallets = ready.concat(Array.isArray(workflow.readyPallets) ? workflow.readyPallets : []); workflow.usedSscc = Array.from(new Set(record.results.map(function (item) { return item.sscc; }).concat(workflow.usedSscc || []))); workflow.crossDockingReassemblies = [record].concat(Array.isArray(workflow.crossDockingReassemblies) ? workflow.crossDockingReassemblies : []); workflow.events = [{ event: "palletsReassembledZE", label: "HU344 · Rearmado en ZE", detail: record.originCount + " origen(es) → 1 resultado · " + record.boxes + " cajas", timestamp: new Date().toLocaleString("es-CO"), status: record.status, sync: record.sync }].concat(Array.isArray(workflow.events) ? workflow.events : []); writeJson(workflowKey, workflow);
    var queue = readJson(syncQueueKey, []); if (!Array.isArray(queue)) queue = []; queue.unshift({ id: "sync-" + record.id, hu: "HU344", title: "Rearmado registrado", subtitle: record.originCount + " origen(es) conciliados en un pallet resultado.", operation: record.operation, entity: "1 pallet resultado", status: "LOCAL_PENDING_SYNC", evidence: 0, attempts: 0, createdAt: new Date().toLocaleString("es-CO"), localId: record.id, idempotencyKey: record.operation + "_palletsReassembledZE_" + record.id, detail: "Linaje de todos los orígenes hacia un único resultado conservado en el dispositivo.", dependency: "" }); writeJson(syncQueueKey, queue);
  }
  function confirmationContent(record) { var content = document.createElement("div"); content.className = "hu344-confirmation"; content.innerHTML = '<div><span>Orígenes</span><strong>' + record.originCount + ' pallets</strong></div><div><span>Resultado</span><strong>1 pallet</strong></div><div><span>Total</span><strong>' + record.boxes + ' cajas</strong></div><div><span>Relación</span><strong>' + record.originCount + ' → 1</strong></div>'; return content; }
  function complete(record) { saveRecord(record); window.SialMobileUI.clearUnsavedChanges(); window.SialMobileUI.showToast({ type: "success", title: "Rearmado registrado", message: record.originCount + " origen(es) quedaron relacionados con un pallet resultado pendiente de sincronización." }); $("[data-hu344-submit]").disabled = true; $("[data-hu344-submit]").textContent = "Rearmado registrado"; $all("input, textarea, select, button", $("[data-hu344-form]")).forEach(function (control) { if (!control.matches("[data-hu344-submit]")) control.disabled = true; }); window.SialMobileUI.setInlineStatus($("[data-flow-error]"), { type: "success", title: "Pallet listo para sincronizar", message: "La composición y el linaje hacia el único resultado quedaron guardados en este dispositivo.", reveal: false }); $("[data-hu344-summary]").scrollIntoView({ behavior: "smooth", block: "center" }); }
  function confirm() { var validation = validateDraft(); if (validation) { showError(validation.message, validation.field); return; } var record = collectRecord(); window.SialMobileUI.openDialog({ id: "hu344-confirm-reassembly", type: "warning", branded: true, title: "Confirmar rearmado", message: "Todos los pallets de origen quedarán relacionados con un único pallet resultado.", content: confirmationContent(record), returnFocus: $("[data-hu344-submit]"), actions: [{ label: "Volver a revisar", variant: "secondary" }, { label: "Confirmar rearmado", onClick: function () { complete(record); } }] }); }
  function wire() {
    hydrateInventoryAdjustments(); render(); $("[data-hu344-select-base]").addEventListener("click", openPalletPicker); $("[data-hu344-base-list]").addEventListener("click", function (event) { var button = event.target.closest("[data-hu344-remove-base]"); if (button) removePallet(button.dataset.hu344RemoveBase); }); $("[data-hu344-base-list]").addEventListener("input", function (event) { if (!event.target.matches("[data-hu344-source-boxes]")) return; var index = Number(event.target.dataset.hu344SourceBoxes), item = selectedPallets[index], reference = event.target.dataset.hu344SourceReference, available = itemComposition(item).find(function (component) { return component.reference === reference; }); initializeTakenComposition(item); var chosen = item.takenComposition.find(function (component) { return component.reference === reference; }), maximum = Number(available ? available.boxes : 0), value = Math.max(0, Math.min(maximum, Number(event.target.value || 0))); chosen.boxes = value; var taken = totalTakenFromPallet(item), takenNode = $('[data-hu344-source-taken="' + index + '"]'), remainingNode = $('[data-hu344-source-remaining="' + index + '"]'); if (takenNode) takenNode.textContent = taken; if (remainingNode) remainingNode.textContent = Number(item.boxes) - taken; resetResults(); renderContext(); renderBalance(); renderResults(); renderSummary(); setNote("[data-hu344-base-status]", totalOriginBoxes() + " cajas seleccionadas para el nuevo armado.", "success"); clearError(); markDirty(); }); $("[data-hu344-base-list]").addEventListener("change", function (event) { if (event.target.matches("[data-hu344-source-reference-toggle]")) { var index = Number(event.target.dataset.hu344SourceReferenceToggle), item = selectedPallets[index], reference = event.target.dataset.hu344SourceReference; initializeTakenComposition(item); var chosen = item.takenComposition.find(function (component) { return component.reference === reference; }), available = itemComposition(item).find(function (component) { return component.reference === reference; }); chosen.selected = event.target.checked; if (chosen.selected && Number(chosen.boxes) < 1) chosen.boxes = Number(available ? available.boxes : 0); resetResults(); clearError(); render(); markDirty(); return; } if (event.target.matches("[data-hu344-source-boxes]")) render(); });
    $("[data-hu344-result-list]").addEventListener("click", function (event) { var scan = event.target.closest("[data-hu344-scan-result]"); if (scan) scanResult(Number(scan.dataset.hu344ScanResult)); });
    $("[data-hu344-result-list]").addEventListener("input", function (event) { if (event.target.matches("[data-hu344-result-sscc]")) { var index = Number(event.target.dataset.hu344ResultSscc); results[index].sscc = event.target.value.replace(/\D/g, "").slice(0, 18); results[index].scanSource = "TYPED"; renderSummary(); markDirty(); } }); $("[data-hu344-result-list]").addEventListener("change", function (event) { if (event.target.matches("[data-hu344-result-sscc]")) render(); }); $("[data-hu344-observations]").addEventListener("input", markDirty); $("[data-hu344-form]").addEventListener("submit", function (event) { event.preventDefault(); confirm(); });
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", wire); else wire();
})();
